language: node_js
node_js:
- 12
before_install:
- npm install -g npm
script:
- npm install
- npm run lint
deploy:
  provider: heroku
  api_key:
    secure: ShRqWl55cHvIaAT1mnsHYColC6mKQFgs/dNGi0kwFKYukbjEWvl7u6JUZHFvS8Um54c0BGmb8vI8gBMfD+x5MaT/SnRvhXrVEHlhiMfmTrn4MakI02VLHtgtLjeESZn7NcXODYFvWrvljXgHK2eIBzzjEdocUeyFGSyyCg1dNYvC+OIKAfe0OrWkYO3OiU9V3b28a9x6LHkb3zVctXNl4Z1RYmb9Ut/kaqJmnz87p7PF5Eb08gxdY3q5iX2e23isetvgMn/kaX+MrVC0do3nZ7qXiKWS0bmHs41EQnra7SijSS4nRhGEJ43mbPUN1323lIfa133dNs455/m0ZwxBwfiq2TZ5bQO/nnEuxn2K7ktuJtZpjZYDsFtcCZcSC1ZuoE19J3EN4U2eqJ0RagdNblywuX/BhMUyP9K3GON2pZRetl0V9Y/Fi117HyoQhDPGPpLhmKVVaHztMoCN4sG85BWpYVk7xQHSNHIJ/aNdYoud9r3GzCvaZs4ZLjwnqAX9e6EFP6S9qPO2REvJcBcufFAd/m2+GCfYvUR/E/6dBnSNwOiHluNb7A2jmrKpF1apHgem0B2vlvmdRPuwiEotOC2k4fqLa1z9OUSQ/AFUPOTzz2zjT0UoC5hX+DlNUIXXFIKMTb7eyFLNPYs6u8XisfLXF7z7zlcbTZPLche8Sb0=
  app: api-havoc-v2
  on:
    repo: Arna-Maity/havoc-v2-rest-api
    branch: master
  skip_cleanup: 'true'
notifications:
  webhooks:
    urls: 
    - secure: "HHz1OiL62/qfvmifYh4UOMMi5kHPVE77SeRcShPdNMezEElo/ILk1V0EuiyPYTEpHpcD+znF4E/9DgeHo1OmtpkPBqKhak4iEXP3Fl0EaIW1HVnLU9OkiO1EhZxgT7KP8wcHHm0F+xrDvn6QIYLnu2Ox0f9SsONAXl2SSkTA8He6OrBrxZJ9LmHE+YSOHz2g3y3ombDqg+OAASaUciVklovHLz5k4BiMyXLmTp8ITLT/0fwgOCNxHKfK97ojcL9NAYPxlNDsDFMXGI1d84Y3bxrnRhTCEP45/kdnnIiRILdwXrGP/tYH/MWhHo3lgAYrP5BeLNvRm/Ovu1wVHO+2nQW/gbJrz1SedGqrrRXiFwEEFK2MPFF6m0s8zl9zxxuIqjD7plyIpQ9K31974mw3+W7LNUlSLFUYI9dPRiaFNwrqymxVyBzcuIAgK/jmEzp++lPEgXvmQ/c6IDrUfLC5rOPOs4QqdRkgVdlPIeDXMLmMOsNGUgvJ0E5awiXaSfO6t9ydQ9jZGUe5zoXNDjmWSk1ga2yJAHpG7zYw+l3NYd8+ICqlEeAQiQRQlClq7xryR6Cf5d51Y25mKaXFblwrpUrgl3jfuRFg5DiJtc6gu63kk0vYbHyuOZHwyLokFVeIum5OrR5TPlun36jRaY/VXNbTD+6PpXK7Qt4hXE5zcvs="
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
