version: '3'
services:
  web:
    env_file:
      - .env
    build: .
    networks:
      - backend
    depends_on: 
      - cache_store
    ports:
      - "3000:3000"
  cache_store:
    image: "redis:alpine"
    networks:
      - backend
    ports: 
      - "6379:6379"

networks:
  backend: